---
- hosts: dockerbuild
  vars:
    image_name: "jberkus/ans101preso"
    image_tag: latest
    owner_email: "josh@agliodbs.com"
    repo_name: "https://github.com/jberkus/ansible101.git"
    webdir_path: "ansible101/preso"
  vars_files:
    - pass.yml
  tasks:
    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - docker
        - git
        - python-docker-py
    - name: write dockerfile
      template:
        src: dockerfile.j2
        dest: /root/Dockerfile
      notify:
        - log into docker hub
        - build docker image
    - name: check out ansible101 repo
      git:
        repo: "{{ repo_name }}"
        dest: /root/ansible101
      notify:
        - log into docker hub
        - build docker image
  handlers:
    - name: log into docker hub
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        email: "{{ owner_email }}"
    - name: build docker image
      docker_image:
        path: /root/
        dockerfile: /root/Dockerfile
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        force: true
