---
# - hosts: dockerbuild
#   vars_files:
#     - pass.yml
#   roles:
#     - dockerbuild

- hosts: localhost
  vars_files:
    - aws.yml
  roles:
    - create_ec2

- hosts: webhosts
  roles:
    - web
