---
- name: Launch instance
  ec2:
     key_name: "{{ keypair }}"
     group: "{{ security_group }}"
     instance_type: "{{ instance_type }}"
     image: "{{ ec2_image }}"
     wait: true
     region: "{{ region }}"
     vpc_subnet_id: "{{ vpc_subnet }}"
     assign_public_ip: yes
     aws_access_key: "{{ aws_access_key }}"
     aws_secret_key: "{{ aws_secret_key }}"
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: webhosts
    ansible_user: centos
    ansible_become: true
  with_items: '{{ec2.instances}}'

- name: Wait for SSH to come up
  wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: '{{ec2.instances}}'
